# This file stores secrets for your Streamlit app.
# IMPORTANT: Add .streamlit/secrets.toml to your .gitignore file!

[connections.snowflake]
account = "ok, is the file being ignored successfully"
user = "and that old entry in git just isn't getting deleted"
password = "and this was all a great lesson in deactivating access keys"
role = "ACCOUNTADMIN"
warehouse = "COMPUTE_WH"
database = "DIGITAL_ASSETS"
schema = "PUBLIC"
