-- Create Database and Schema for the FHOA Ontology
CREATE DATABASE IF NOT EXISTS FHOA_ONTOLOGY_DB;
CREATE SCHEMA IF NOT EXISTS FHOA_ONTOLOGY_DB.IDEF0_SCHEMA;

USE DATABASE FHOA_ONTOLOGY_DB;
USE SCHEMA IDEF0_SCHEMA;

-- Table for high-level model definitions
CREATE OR REPLACE TABLE MODELS (
    MODEL_ID NUMBER(38,0) PRIMARY KEY,
    MODEL_NAME VARCHAR(255) NOT NULL
);

-- Table for FUNCTIONS (the boxes)
CREATE OR REPLACE TABLE FUNCTIONS (
    FUNCTION_ID NUMBER(38,0) PRIMARY KEY,
    MODEL_ID NUMBER(38,0) NOT NULL,
    FUNCTION_NAME VARCHAR(255) NOT NULL,
    PARENT_FUNCTION_ID NUMBER(38,0),
    CONSTRAINT FK_FUNCTION_MODEL FOREIGN KEY (MODEL_ID) REFERENCES MODELS(MODEL_ID),
    CONSTRAINT FK_PARENT_FUNCTION FOREIGN KEY (PARENT_FUNCTION_ID) REFERENCES FUNCTIONS(FUNCTION_ID)
);

-- Table for ENTITIES (the conceptual "things" or arrows)
CREATE OR REPLACE TABLE ENTITIES (
    ENTITY_ID NUMBER(38,0) PRIMARY KEY,
    ENTITY_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000)
);

-- The core junction table for all connections
CREATE OR REPLACE TABLE FUNCTION_ENTITIES (
    FUNCTION_ENTITY_ID NUMBER(38,0) PRIMARY KEY,
    FUNCTION_ID NUMBER(38,0) NOT NULL,
    ENTITY_ID NUMBER(38,0) NOT NULL,
    ROLE VARCHAR(50) NOT NULL COMMENT 'INPUT, CONTROL, OUTPUT, or MECHANISM',
    
    -- Link to the parent FUNCTION_ENTITIES record for bundling
    PARENT_FUNCTION_ENTITY_ID NUMBER(38,0),

    -- Source Traceability Columns for external/cross-model arrows
    SOURCE_MODEL_ID NUMBER(38,0),
    SOURCE_FUNCTION_ID NUMBER(38,0),
    SOURCE_ENTITY_ID NUMBER(38,0),

    -- Visual Metadata Columns
    TUNNEL_STATUS VARCHAR(50) DEFAULT 'NONE' COMMENT 'e.g., NONE, TUNNELED_AT_SOURCE, TUNNELED_AT_DESTINATION',

    -- Foreign Key Constraints
    CONSTRAINT FK_FE_FUNCTION FOREIGN KEY (FUNCTION_ID) REFERENCES FUNCTIONS(FUNCTION_ID),
    CONSTRAINT FK_FE_ENTITY FOREIGN KEY (ENTITY_ID) REFERENCES ENTITIES(ENTITY_ID),
    CONSTRAINT FK_FE_PARENT_FE FOREIGN KEY (PARENT_FUNCTION_ENTITY_ID) REFERENCES FUNCTION_ENTITIES(FUNCTION_ENTITY_ID),
    CONSTRAINT FK_SOURCE_MODEL FOREIGN KEY (SOURCE_MODEL_ID) REFERENCES MODELS(MODEL_ID),
    CONSTRAINT FK_SOURCE_FUNCTION FOREIGN KEY (SOURCE_FUNCTION_ID) REFERENCES FUNCTIONS(FUNCTION_ID),
    CONSTRAINT FK_SOURCE_ENTITY FOREIGN KEY (SOURCE_ENTITY_ID) REFERENCES ENTITIES(ENTITY_ID)
);