-- Snowflake patch to align with the UI data model
CREATE OR REPLACE TABLE IF NOT EXISTS DIAGRAMS (
  DIAGRAM_ID NUMBER(38,0) PRIMARY KEY,
  MODEL_ID NUMBER(38,0) NOT NULL,
  NODE VARCHAR(32) NOT NULL,
  TITLE VARCHAR(255),
  AUTHOR VARCHAR(255),
  STATUS VARCHAR(32),
  CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_AT TIMESTAMP_NTZ
);

ALTER TABLE IF EXISTS FUNCTIONS ADD COLUMN IF NOT EXISTS X NUMBER(10,0);
ALTER TABLE IF EXISTS FUNCTIONS ADD COLUMN IF NOT EXISTS Y NUMBER(10,0);
ALTER TABLE IF EXISTS FUNCTIONS ADD COLUMN IF NOT EXISTS W NUMBER(10,0);
ALTER TABLE IF EXISTS FUNCTIONS ADD COLUMN IF NOT EXISTS H NUMBER(10,0);
ALTER TABLE IF EXISTS FUNCTIONS ADD COLUMN IF NOT EXISTS BOX_NUMBER VARCHAR(8);
ALTER TABLE IF EXISTS FUNCTIONS ADD COLUMN IF NOT EXISTS KIND VARCHAR(20) DEFAULT 'FUNCTION';

CREATE OR REPLACE TABLE IF NOT EXISTS CONNECTORS (
  CONNECTOR_ID NUMBER(38,0) PRIMARY KEY,
  MODEL_ID NUMBER(38,0) NOT NULL,
  A_FUNCTION_ID NUMBER(38,0) NOT NULL,
  A_SIDE VARCHAR(10) NOT NULL,
  A_ROLE VARCHAR(2) NOT NULL,
  B_FUNCTION_ID NUMBER(38,0) NOT NULL,
  B_SIDE VARCHAR(10) NOT NULL,
  B_ROLE VARCHAR(2) NOT NULL,
  LABEL VARCHAR(255)
);

CREATE OR REPLACE TABLE IF NOT EXISTS STUBS (
  STUB_ID NUMBER(38,0) PRIMARY KEY,
  MODEL_ID NUMBER(38,0) NOT NULL,
  FUNCTION_ID NUMBER(38,0) NOT NULL,
  SIDE VARCHAR(10) NOT NULL,
  ROLE VARCHAR(2) NOT NULL,
  AXIS VARCHAR(1) NOT NULL,
  OFFSET NUMBER(10,0) DEFAULT 0,
  LENGTH NUMBER(10,0) DEFAULT 80,
  DIR NUMBER(2,0) DEFAULT 1,
  LABEL VARCHAR(255),
  TUNNEL_STATUS VARCHAR(50) DEFAULT 'NONE',
  ICOM_CODE VARCHAR(8)
);

CREATE OR REPLACE TABLE IF NOT EXISTS ENTITY_CATALOG (
  ENTITY_ID NUMBER(38,0) PRIMARY KEY,
  ENTITY_NAME VARCHAR(255) NOT NULL UNIQUE
);
