-- use sysadmin to create the database and schema
USE ROLE SYSADMIN;

-- Create Database and Schema for the FHOA Ontology
-- Create Database and Schema for the Ontologics Framework
CREATE DATABASE IF NOT EXISTS ONTOLOGICS;
CREATE SCHEMA IF NOT EXISTS ONTOLOGICS.IDEF0;

USE DATABASE ONTOLOGICS;
USE SCHEMA IDEF0;

-- Table for high-level model definitions
CREATE OR REPLACE TABLE MODELS (
    MODEL_ID NUMBER(38,0) PRIMARY KEY, -- Note: ID is managed by the application layer, not auto-incremented.
    MODEL_NAME VARCHAR(255) NOT NULL,
    NODE VARCHAR(10)
);

-- Table for FUNCTIONS (the boxes)
CREATE OR REPLACE TABLE FUNCTIONS (
    FUNCTION_ID NUMBER(38,0) PRIMARY KEY, -- Note: ID is managed by the application layer. This allows for pre-linking parent/child relationships before ingestion.
    MODEL_ID NUMBER(38,0) NOT NULL,
    NODE VARCHAR(10),
    FUNCTION_NAME VARCHAR(255) NOT NULL,
    PARENT_FUNCTION_ID NUMBER(38,0),
    CONSTRAINT FK_FUNCTION_MODEL FOREIGN KEY (MODEL_ID) REFERENCES MODELS(MODEL_ID),
    CONSTRAINT FK_PARENT_FUNCTION FOREIGN KEY (PARENT_FUNCTION_ID) REFERENCES FUNCTIONS(FUNCTION_ID)
);

-- Table for ENTITIES (the conceptual "things" or arrows)
CREATE OR REPLACE TABLE ENTITIES (
    ENTITY_ID NUMBER(38,0) PRIMARY KEY, -- Note: ID is managed by the application layer.
    EDGE VARCHAR(255),
    ENTITY_NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000)
);

-- The core junction table for all connections
CREATE OR REPLACE TABLE FUNCTION_ENTITIES (
    FUNCTION_ENTITY_ID NUMBER(38,0) PRIMARY KEY, -- Note: ID is managed by the application layer. This facilitates the creation of ICOM bundles.
    FUNCTION_ID NUMBER(38,0) NOT NULL,
    ENTITY_ID NUMBER(38,0) NOT NULL,
    ROLE VARCHAR(50) NOT NULL COMMENT 'INPUT, CONTROL, OUTPUT, or MECHANISM',
    EDGE VARCHAR(255), --bundle name for grouping arrows
    -- Link to the parent FUNCTION_ENTITIES record for bundling
    PARENT_FUNCTION_ENTITY_ID NUMBER(38,0),

    -- Source Traceability Columns for external/cross-model arrows
    SOURCE_MODEL_ID NUMBER(38,0),
    SOURCE_FUNCTION_ID NUMBER(38,0),
    SOURCE_ENTITY_ID NUMBER(38,0),

    -- Visual Metadata Columns
    TUNNEL_STATUS VARCHAR(50) DEFAULT 'NONE' COMMENT 'e.g., NONE, TUNNELED_AT_SOURCE, TUNNELED_AT_DESTINATION',

    -- Foreign Key Constraints
    CONSTRAINT FK_FE_FUNCTION FOREIGN KEY (FUNCTION_ID) REFERENCES FUNCTIONS(FUNCTION_ID),
    CONSTRAINT FK_FE_ENTITY FOREIGN KEY (ENTITY_ID) REFERENCES ENTITIES(ENTITY_ID),
    CONSTRAINT FK_FE_PARENT_FE FOREIGN KEY (PARENT_FUNCTION_ENTITY_ID) REFERENCES FUNCTION_ENTITIES(FUNCTION_ENTITY_ID),
    CONSTRAINT FK_SOURCE_MODEL FOREIGN KEY (SOURCE_MODEL_ID) REFERENCES MODELS(MODEL_ID),
    CONSTRAINT FK_SOURCE_FUNCTION FOREIGN KEY (SOURCE_FUNCTION_ID) REFERENCES FUNCTIONS(FUNCTION_ID),
    CONSTRAINT FK_SOURCE_ENTITY FOREIGN KEY (SOURCE_ENTITY_ID) REFERENCES ENTITIES(ENTITY_ID)
);